### ISSUE TITLE
Failed installing zsh theme and other stuff

### ISSUE THREAD

**Issue by Anifyuli** [mayTermux/myTermux#35]
Hello, Bro.
I have a problem in installing dotfiles, especially zsh theme and NvChad.
How you can fix it, thanks
![Screenshot_2022-02-26-23-19-41-00_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73734843/155850734-8a9e0c48-1c09-4c1a-b0f4-1559135ccbae.jpg)
 I love it ❤️

**Comment by Anifyuli** [comment]
Yes, I install git and bc too before execute installer script

**Comment by nihsx** [comment]
> Yes, I install git and bc too before execute installer script ![Screenshot_2022-02-26-23-31-36-11_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/73734843/155851028-3b20c5d8-5593-4054-bd96-fb92903f36be.jpg)

hmm, I have no idea it should be run normally.  To fix it maybe you can do manual installation 

- [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh#basic-installation)
- [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh)
- [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#manual-git-clone)
- [tmux-themepack](https://github.com/jimeh/tmux-themepack#install-manually)
- [NvChad](https://nvchad.netlify.app/getting-started/setup#linux--macos)

and for zsh custom theme you can manually copy all theme into folder `~/.oh-my-zsh/custom/themes/` after [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh#basic-installation) installed

**Comment by Anifyuli** [comment]
Problem solved after installing several libraries. Thanks, Bro

**Comment by nihsx** [comment]
> Problem solved after installing several libraries. Thanks, Bro

ok bro, i will close this issue
