### ISSUE TITLE
Request add features

### ISSUE THREAD

**Issue by swcodec** [mayTermux/myTermux#36]
Is it possible to add nushell?

[Nushell website](https://www.nushell.sh/)

**Comment by nihsx** [comment]
> Is it possible to add nushell?
> 
> [Nushell website](https://www.nushell.sh/)

You can install Nushell manually with command: `pkg i nushell`

![Screenshot_20220325-201557_Termux](https://user-images.githubusercontent.com/66439853/160128229-1b06bd40-3890-4977-a7bb-5bba4d87e7d3.png)

![Screenshot_20220325-201737_Termux](https://user-images.githubusercontent.com/66439853/160128274-3c0459aa-1061-45e0-8282-553f01b9e716.png)

**Comment by swcodec** [comment]
> > Is it possible to add nushell?
> > [Nushell website](https://www.nushell.sh/)
> 
> You can install Nushell manually with command: `pkg i nushell`
> 
> ![Screenshot_20220325-201557_Termux](https://user-images.githubusercontent.com/66439853/160128229-1b06bd40-3890-4977-a7bb-5bba4d87e7d3.png)
> 
> ![Screenshot_20220325-201737_Termux](https://user-images.githubusercontent.com/66439853/160128274-3c0459aa-1061-45e0-8282-553f01b9e716.png)

what about the configuration file, is it possible for you to also custom the nushell prompt, because the default prompt doesn't really suit me 😅

**Comment by nihsx** [comment]
Sorry i'm not interested in `nushell`
