### ISSUE TITLE
NVIM dumping everything text I'm deleting in my clipboard  isn't FUNNY

### ISSUE THREAD

**Issue by z8512** [mayTermux/myTermux#37]
Atleast tell me how to disable neovim dumping everything in my clipbaord. I've important notes in clipboard.
I request you to disable it

**Comment by nihsx** [comment]
> Atleast tell me how to disable neovim dumping everything in my clipbaord. I've important notes in clipboard. I request you to disable it

![Screenshot_20220331-142017_Termux](https://user-images.githubusercontent.com/66439853/161000178-a641346b-76af-41ea-beb6-95b491360299.png)

Just delete value clipboard `unnamedplus` on `~/.config/nvim/lua/default_config.lua`

References: https://github.com/editor-bootstrap/vim-bootstrap/issues/300#issuecomment-428473621

**Btw, I'm not a NvChad creator, if you have problems with nvim go to the [NvChad](https://github.com/NvChad/NvChad) repository or find out yourself by googling, don't be spoiled**

**Comment by z8512** [comment]
Okay

**Comment by z8512** [comment]
Wait  ~/.config/nvim/lua/default_config.lua file doesn't exist

**Comment by z8512** [comment]
Its `~/.config/nvim/core/default_config.lua` actually.
How fo you have in ~/.config/nvim/lua/default_config.lua ?

**Comment by nihsx** [comment]
`~/.config/nvim/lua/core/default_config.lua`
