### ISSUE TITLE
How to close it

### ISSUE THREAD

**Issue by sukansingh946** [mayTermux/myTermux#38]
How to close this them

**Comment by armandwipangestu** [comment]
> How to close this them

What do you mean `close this them`

**Comment by sukansingh946** [comment]
I want to close this them

**Comment by sukansingh946** [comment]
This script

**Comment by sukansingh946** [comment]
Want old termux them

**Comment by sukansingh946** [comment]
Theme sorry 😹

**Comment by armandwipangestu** [comment]
> Want old termux them

Just deleted all the `files` or `directory` related with this setup and rename the backup `files` or `directory` with the suffix `file/dir.date.backup` on `$HOME`

**NOTE: The quick way is, just `clear cache` and `clear data` Termux application**
