### ISSUE TITLE
Everblush

### ISSUE THREAD

**Issue by Mangeshrex** [mayTermux/myTermux#45]
maybe try this colorscheme https://github.com/Everblush/termux

**Comment by armandwipangestu** [comment]
[done](https://github.com/mayTermux/myTermux/blob/main/.colorscheme/everblush.colors) 

![Screenshot_20220808_200305](https://user-images.githubusercontent.com/64394320/183424960-e0720fdb-f987-49fb-8938-8a876ae0f82a.png)

**Comment by Mangeshrex** [comment]
uwu
