### ISSUE TITLE
Questions💝

### ISSUE THREAD

**Issue by Blacklegion69** [mayTermux/myTermux#46]
**I have 2 questions** 
1. How can I change neovim color scheme (I have some colorscheme file)
2. How to enable nerd tree in neovim ?? I found a file in nvim/plugins

the file path is 
/data/data/com.termux/files/home/.config/nvim/plugin/packer_compiled.lua
Line number 245

**Comment by armandwipangestu** [comment]
I don't really understand to NvChad, if you have problems, please visit the [official repository](https://github.com/NvChad/NvChad) or [telegram group](https://t.me/DE_WM)
