### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by montouchmohaimin** [mayTermux/myTermux#48]
how can i play music with this?

**Comment by armandwipangestu** [comment]
## How to play Music?

- First you need to run Music Player Daemon, with command:

```bash
mpd
```

- After Music Player Daemon running, open Ncmpcpp with command:

```bash
ncmpcpp
```

> **NOTE**: Make sure your mpd and ncmpcpp configurations in the `music_directory` & `mpd_music_dir` section are correct with your music file path
>
> | `~/.config/mpd/mpd.conf` | `~/.config/ncmpcpp/config` |
> |--|--|
> |![image](https://user-images.githubusercontent.com/64394320/187211481-eba36896-9d16-4fc0-8734-59db63e88ef5.png)|![image](https://user-images.githubusercontent.com/64394320/187211701-de18f8e2-1404-4ac1-8a95-8922632e1ba3.png)|
