### ISSUE TITLE
Termux theme issue

### ISSUE THREAD

**Issue by Dawood80** [mayTermux/myTermux#52]
Helo sir how are you?
I want to delete theme from my termux which I am using but I want to restore it back to original version without deleting my termux or clearing its data because I am using paid commands I will lose its subscription did you have any way to delete theme???

**Comment by armandwipangestu** [comment]
Do you mean the theme is a color scheme?

If that is what you mean, then just run the following command:

### Remove current color scheme you use

``` bash
rm ~/.termux/colors.properties
```

### Reload termux setting

``` bash
termux-reload-settings
```

**Comment by armandwipangestu** [comment]
> Thanks I remove it but how to switch to it's original keyboard? I want to switch to termux setting keyboard

Did you mean `Extra Key Rows`?

![extra-keys](https://user-images.githubusercontent.com/64394320/195278937-adce38bd-3e8d-4eca-b962-52cf0be4dbfd.png)

Read Termux Wiki for this https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row

**Comment by Dawood80** [comment]
Yes my Key board is like this I want to remove this keyboard and I want to restore it to termux keyboard

**Comment by Dawood80** [comment]
![Screenshot_2022-10-15-13-32-19-820_com termux](https://user-images.githubusercontent.com/90832305/195977480-3f1535ab-a963-4654-9fd0-e0347282af27.jpg)
Not working it denied permission
