### ISSUE TITLE
bc: command not found

### ISSUE THREAD

**Issue by buddhhu** [mayTermux/myTermux#53]
I am getting this while installation 
![Screenshot_2022-12-03-21-59-27-709_com termux](https://user-images.githubusercontent.com/48654350/205451327-fda59166-548b-45b8-bdba-26554a90fc10.jpg)

**Comment by rendykyh** [comment]
before ./install you need to install bc and git

**Comment by buddhhu** [comment]
> before ./install you need to install bc and git

I did. Actually it isn't mentioned in readme, so I thought only git (to clone) will be required.

**Comment by armandwipangestu** [comment]
> I did. Actually it isn't mentioned in readme, so I thought only git (to clone) will be required.

it is mentioned in the readme

![image](https://user-images.githubusercontent.com/64394320/205910622-b3a9f9dd-8bd2-4e46-a60c-3aa50e4ef77b.png)
