### ISSUE TITLE
after apply this theme ls cmd not working.

### ISSUE THREAD

**Issue by spidy2356** [mayTermux/myTermux#67]
as title says, ls cmd not works after apply these theme. when I give ls cmd it says to install exa pkg. but when I install exa it says no candidate available.

solution I found: rm -rf $PREFIX
 so, it remove ur ur all installed pkgs, header, and problem also get fix but termux data will not deleted and theme also be ok
 
 to remove theme fully here is the guide: https://youtu.be/WrlW3DozpYk

**Comment by armandwipangestu** [comment]
no, package `exa` is available on repository termux so it should be installable

if you don't want to use exa as default ls command, you can just give comment or remove the alias in the `.aliases` file

remove all the package on `$PREFIX` is wild and waste your time to setup all the package. No worth it.

**Comment by armandwipangestu** [comment]
![Screenshot_20240130_001603](https://github.com/mayTermux/myTermux/assets/64394320/81b9ba78-71b1-4bb5-aa25-7015cce2e959)
