### ISSUE TITLE
Exa package is deprecated, use eza instead.

### ISSUE THREAD

**Issue by kryptobolt200528** [mayTermux/myTermux#68]
The ls command stops working after installation due to exa being deprecated.
.

**Comment by armandwipangestu** [comment]
Thanks for the information, someone just open a pull request to change the `exa` package to `eza` package and now has been merged to the main branch https://github.com/mayTermux/myTermux/pull/71

**Comment by Rahullslam** [comment]
@kryptobolt200528 
 _**
## 
# __~~~~ _ _ ** _
