### ISSUE TITLE
Battery status won't display on neofetch

### ISSUE THREAD

**Issue by EdibleQueso42** [mayTermux/myTermux#77]
So when I type neo, the battery status is just blank![Screenshot_2024-10-17-21-13-48-33_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/62fcbd42-9b99-4367-8f14-9356bb3b7753)

**Comment by armandwipangestu** [comment]
You must install `Termux:API` application to make `termux-api` package can fetch the battery information

**Comment by EdibleQueso42** [comment]
Well... I have it already but after inspecting the config.conf, there's no option 2 for battery on fetch.sh

**Comment by armandwipangestu** [comment]
| Fetch Script | Neofetch Configuration |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/ed01bdde-03ed-4b96-9d93-88493fd34141) | ![image](https://github.com/user-attachments/assets/748a580e-4005-4a31-abf6-8767a3380e1f) |

**Comment by EdibleQueso42** [comment]
Weird, btw I'm using version 0.6.2

**Comment by EdibleQueso42** [comment]
Update:
So it only does that only if it's discharge, if I plug it, it will display it

**Comment by EdibleQueso42** [comment]
I found the solution! Edit fetch.sh, on line 228, replace `DISCHARGING` with `NOT_CHARGING`
